# BLE スプリット（2ペリフェラル: 左+右）
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_BT_MAX_CONN=7
CONFIG_BT_MAX_PAIRED=7

# ポインティングデバイス
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_MOUSE=y
CONFIG_INPUT=y

# センサー回転
CONFIG_SENSOR_ROTATION=y

# バッテリー
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# スリープ（アイドル化もスリープも 1h まで遅延、据え置き運用のため反応性優先）
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=3600000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# Prospector（beekeeb版：近接センサー非搭載）
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=80
